# Generated by Django 5.2.4 on 2026-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_capacity_event_category_event_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
