# Generated by Django 5.2 on 2025-10-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="has_certification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="program",
            name="mode",
            field=models.CharField(
                choices=[
                    ("Online", "Online"),
                    ("Hybrid", "Hybrid"),
                    ("On-site", "On-site"),
                ],
                default="Online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="modules",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of modules", null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="prerequisites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="scholarship_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="program",
            name="sessions_per_week",
            field=models.IntegerField(default=3),
        ),
    ]
