# Generated by Django 5.2 on 2025-10-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_program_has_certification_program_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="image",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
