# Generated by Django 5.2 on 2025-10-12 03:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_alter_program_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
