# Generated by Django 5.2 on 2025-10-12 02:36

from django.db import migrations


def clear_long_image_urls(apps, schema_editor):
    """Clear image URLs that are too long for CloudinaryField"""
    Program = apps.get_model('programs', 'Program')
    # Set empty string for all existing image URLs
    # They can be re-uploaded via Cloudinary later
    Program.objects.all().update(image='')


def reverse_clear_urls(apps, schema_editor):
    """Reverse migration - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0005_alter_program_image"),
    ]

    operations = [
        migrations.RunPython(clear_long_image_urls, reverse_clear_urls),
    ]
