# Generated by Django 5.2.4 on 2026-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20251012_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coupon',
            field=models.CharField(blank=True, default='%coupon', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
