# Generated by Django 5.2.4 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_coupon_program_is_paid_program_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
