# Generated by Django 5.2.4 on 2026-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("general", "General Contact"),
                            ("sponsor", "Partner as Sponsor"),
                            ("education", "Education & Training Partner"),
                        ],
                        help_text="Type of contact page",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title displayed on the page", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle below the main title", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description text"),
                ),
                (
                    "default_subject",
                    models.CharField(
                        blank=True,
                        help_text="Pre-filled subject for the contact form",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "default_message",
                    models.TextField(
                        blank=True,
                        help_text="Pre-filled message for the contact form",
                        null=True,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Send Message",
                        help_text="Text for the submit button",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this contact type is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Page Setting",
                "verbose_name_plural": "Contact Page Settings",
                "ordering": ["contact_type"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Code2Deploy", max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "contact_email",
                    models.EmailField(default="info@code2deploy.com", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("footer_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
