# Generated by Django 5.2.4 on 2026-01-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpagesettings",
            name="contact_info_title",
            field=models.CharField(
                default="Ping Our Network",
                help_text="Title for the contact info section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="email_label",
            field=models.CharField(
                default="Email Us",
                help_text="Label for the email section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="phone_hours",
            field=models.CharField(
                default="Mon-Fri: 9AM-6PM WAT",
                help_text="Business hours",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="phone_label",
            field=models.CharField(
                default="Call Us",
                help_text="Label for the phone section",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="phone_number",
            field=models.CharField(
                default="+254 743 864 7890",
                help_text="Contact phone number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="primary_email",
            field=models.EmailField(
                default="info@code2deploy.com",
                help_text="Primary contact email",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="secondary_email",
            field=models.EmailField(
                blank=True,
                default="support@code2deploy.com",
                help_text="Secondary contact email (optional)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="visit_address",
            field=models.TextField(
                default="123 Tech Hub, Innovation Street\nLagos, Nigeria",
                help_text="Physical address",
            ),
        ),
        migrations.AddField(
            model_name="contactpagesettings",
            name="visit_label",
            field=models.CharField(
                default="Visit Us",
                help_text="Label for the address section",
                max_length=100,
            ),
        ),
    ]
