# Generated by Django 5.2.4 on 2026-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0002_contactpagesettings_contact_info_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="About Code2Deploy", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Empowering African youth with cutting-edge tech skills",
                        max_length=300,
                    ),
                ),
                ("hero_image_url", models.URLField(blank=True, null=True)),
                (
                    "mission_title",
                    models.CharField(default="Our Mission", max_length=100),
                ),
                (
                    "mission_description",
                    models.TextField(
                        default="To bridge the digital skills gap in Africa by providing world-class technology education and creating pathways to successful careers in the global tech industry."
                    ),
                ),
                (
                    "vision_title",
                    models.CharField(default="Our Vision", max_length=100),
                ),
                (
                    "vision_description",
                    models.TextField(
                        default="To be Africa's leading technology education platform, empowering the next generation of tech leaders and innovators who will drive the continent's digital transformation."
                    ),
                ),
                (
                    "journey_title",
                    models.CharField(default="Our Journey", max_length=100),
                ),
                (
                    "team_title",
                    models.CharField(default="Our Leadership Team", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page Setting",
                "verbose_name_plural": "About Page Settings",
            },
        ),
        migrations.CreateModel(
            name="EventsPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Upcoming Events", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Join us for exciting tech events, workshops, and networking opportunities",
                        max_length=300,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        default="Stay connected with the Code2Deploy community through our events.",
                    ),
                ),
                (
                    "events_section_title",
                    models.CharField(default="All Events", max_length=100),
                ),
                (
                    "no_events_message",
                    models.CharField(
                        default="No upcoming events at the moment. Check back soon!",
                        max_length=200,
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(default="Want to Host an Event?", max_length=200),
                ),
                (
                    "cta_description",
                    models.TextField(
                        default="Partner with us to bring tech events to your community."
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Contact Us", max_length=50),
                ),
                (
                    "cta_button_link",
                    models.CharField(default="/contact", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Events Page Setting",
                "verbose_name_plural": "Events Page Settings",
            },
        ),
        migrations.CreateModel(
            name="HomePageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title_line1", models.CharField(default="From", max_length=100)),
                (
                    "hero_title_highlight1",
                    models.CharField(default="Hello World", max_length=100),
                ),
                ("hero_title_line2", models.CharField(default="to", max_length=100)),
                (
                    "hero_title_highlight2",
                    models.CharField(default="Hello AI", max_length=100),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Empowering African youth with cutting-edge tech skills to build solutions that matter. Join our community of innovators today."
                    ),
                ),
                (
                    "hero_button1_text",
                    models.CharField(default="Join a Program", max_length=50),
                ),
                (
                    "hero_button1_link",
                    models.CharField(default="/programs", max_length=200),
                ),
                (
                    "hero_button2_text",
                    models.CharField(default="Upcoming Events", max_length=50),
                ),
                (
                    "hero_button2_link",
                    models.CharField(default="/events", max_length=200),
                ),
                ("hero_image_url", models.URLField(blank=True, null=True)),
                (
                    "approach_title",
                    models.CharField(default="Our Approach", max_length=100),
                ),
                (
                    "approach_description",
                    models.TextField(
                        default="Most courses stop at code. We take you further. By the end of our program, you'll have:"
                    ),
                ),
                (
                    "what_we_do_title",
                    models.CharField(default="What We Do", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page Setting",
                "verbose_name_plural": "Home Page Settings",
            },
        ),
        migrations.CreateModel(
            name="ProgramsPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Our Programs", max_length=200),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="Discover world-class technology programs designed for African youth",
                        max_length=300,
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        blank=True,
                        default="From beginner to advanced, our programs are designed to take you from where you are to where you want to be in tech.",
                    ),
                ),
                (
                    "programs_section_title",
                    models.CharField(default="Available Programs", max_length=100),
                ),
                (
                    "no_programs_message",
                    models.CharField(
                        default="No programs available at the moment. Check back soon!",
                        max_length=200,
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Ready to Start Your Journey?", max_length=200
                    ),
                ),
                (
                    "cta_description",
                    models.TextField(
                        default="Join thousands of students who have transformed their careers through our programs."
                    ),
                ),
                (
                    "cta_button_text",
                    models.CharField(default="Apply Now", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Programs Page Setting",
                "verbose_name_plural": "Programs Page Settings",
            },
        ),
    ]
