# Generated by Django 5.2.4 on 2026-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0003_aboutpagesettings_eventspagesettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_button1_link",
            field=models.CharField(default="/programs", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_button1_text",
            field=models.CharField(default="Apply Now", max_length=50),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_button2_link",
            field=models.CharField(default="/contact", max_length=200),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_button2_text",
            field=models.CharField(default="Schedule a Call", max_length=50),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_description",
            field=models.TextField(
                default="Join our community of learners and innovators today. Take the first step toward a future in technology."
            ),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="cta_title",
            field=models.CharField(
                default="Ready to Start Your Tech Journey?", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="homepagesettings",
            name="programs_section_title",
            field=models.CharField(default="Our Programs", max_length=100),
        ),
    ]
