# Generated by Django 5.2.4 on 2026-01-12 05:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_homepagesettings_cta_button1_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesettings',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='hero_image_url',
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
    ]
