# Generated by Django 5.2.4 on 2026-01-12 07:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_remove_aboutpagesettings_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspagesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AddField(
            model_name='programspagesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
    ]
