# Generated by Django 5.2.4 on 2026-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_eventspagesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagesettings',
            name='team_title',
        ),
        migrations.RemoveField(
            model_name='eventspagesettings',
            name='cta_button_link',
        ),
        migrations.RemoveField(
            model_name='programspagesettings',
            name='cta_button_text',
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic sections for the about page'),
        ),
        migrations.AddField(
            model_name='eventspagesettings',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic sections for the events page'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic sections for the home page'),
        ),
        migrations.AddField(
            model_name='programspagesettings',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic sections for the programs page'),
        ),
    ]
