# Generated by Django 5.2.4 on 2026-01-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_remove_aboutpagesettings_team_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesettings',
            name='team_title',
            field=models.CharField(default='Our Leadership Team', max_length=100),
        ),
        migrations.AddField(
            model_name='eventspagesettings',
            name='cta_button_link',
            field=models.CharField(default='/contact', max_length=200),
        ),
        migrations.AddField(
            model_name='programspagesettings',
            name='cta_button_text',
            field=models.CharField(default='Apply Now', max_length=50),
        ),
    ]
