# Generated by Django 5.2.4 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_aboutpagesettings_team_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
        migrations.AlterField(
            model_name='eventspagesettings',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
        migrations.AlterField(
            model_name='programspagesettings',
            name='hero_image',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
