# Generated by Django 5.2.4 on 2025-07-26 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("error_rate", models.FloatField(blank=True, null=True)),
                ("uptime", models.FloatField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["component", "status"],
                        name="security_sy_compone_bb1019_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="security_sy_created_792720_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                            ("email_confirmation", "Email Confirmation"),
                            ("account_deletion", "Account Deletion"),
                            ("enrollment", "Program Enrollment"),
                            ("registration", "Event Registration"),
                            ("certificate_issued", "Certificate Issued"),
                            ("badge_awarded", "Badge Awarded"),
                            ("admin_action", "Admin Action"),
                            ("security_event", "Security Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="security_au_user_id_61e86d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="security_au_created_82f799_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="security_au_ip_addr_083b2c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataPrivacyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("data_export", "Data Export"),
                            ("data_deletion", "Data Deletion"),
                            ("consent_given", "Consent Given"),
                            ("consent_withdrawn", "Consent Withdrawn"),
                            ("data_access", "Data Access"),
                            ("data_rectification", "Data Rectification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("data_categories", models.JSONField(blank=True, default=list)),
                ("legal_basis", models.CharField(blank=True, max_length=100)),
                ("retention_period", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action"], name="security_da_user_id_1da8de_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="security_da_created_1b048f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("register", "Register"),
                            ("password_reset", "Password Reset"),
                            ("api_request", "API Request"),
                            ("email_send", "Email Send"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_count", models.PositiveIntegerField()),
                ("limit_threshold", models.PositiveIntegerField()),
                ("window_seconds", models.PositiveIntegerField()),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("allowed", "Allowed"),
                            ("blocked", "Blocked"),
                            ("delayed", "Delayed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rate_limit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["limit_type", "ip_address"],
                        name="security_ra_limit_t_4be341_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="security_ra_created_85ae54_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Failed Login"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("data_breach", "Data Breach"),
                            ("malware_detected", "Malware Detected"),
                            ("account_compromise", "Account Compromise"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "severity"],
                        name="security_se_event_t_5077ff_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="security_se_resolve_f02b32_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="security_se_created_841554_idx"
                    ),
                ],
            },
        ),
    ]
