# Generated by Django 5.2.4 on 2026-01-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_github_mentor_is_active_mentor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
