# Generated by Django 5.2.4 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_hourly_rate_mentor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_file',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
        migrations.AlterField(
            model_name='mentorresource',
            name='file',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
