# Generated by Django 5.2.4 on 2025-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="unique_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
