# Generated by Django 5.2.4 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
