# Generated by Django 5.2.4 on 2026-01-12 05:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='badge'),
        ),
    ]
