# Generated by Django 5.2.4 on 2026-01-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_badge_icon_url_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.TextField(blank=True, help_text='Cloudinary ID or external URL', null=True),
        ),
    ]
